[ADD] mrp_cut: Second UOM and second UOM quantity in MRP BOM line.
avanzosc/mrp-addons pull request #124
Opened 2021-11-25 13:24 UTC by Berezi

2021-11-25 13:24 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-12-10 06:34 UTC, alfredoavanzosc approved these changes

2021-12-16 14:52 UTC, Daniel-CA requested changes

2021-12-16 14:52 UTC, Daniel-CA commented on mrp_cut/README.rst
> +* Second UOM and second UOM quantity in MRP BOM line.
Si el módulo añade una UoM nueva debería llamarse mrp_bom_second_uom o similar

2021-12-17 08:53 UTC, Berezi commented on mrp_cut/README.rst
> +* Second UOM and second UOM quantity in MRP BOM line.
El nombre se lo puso Ana.

2021-12-23 14:06 UTC, oihane commented on mrp_cut/README.rst
> +* Long cut, pieces second UOM, second UOM and second UOM quantity in MRP BOM line.
Si no es un listado sobra el *

2022-01-10 10:50 UTC, anajuaristi approved these changes

2022-01-10 10:52 UTC, Daniel-CA approved these changes

2022-01-10 10:56 UTC, merged