[ADD] mrp_production_duration: Put total to "expected duration" and "…
avanzosc/mrp-addons pull request #171
Opened 2022-06-07 11:26 UTC by alfredoavanzosc

…duration" fields.

2022-06-07 11:27 UTC, alfredoavanzosc commented
@avanzosc/developers ... review please.

2022-06-07 12:31 UTC, anajuaristi submitted a review, later dismissed

2022-06-07 12:31 UTC, anajuaristi commented on mrp_production_duration/views/mrp_workorder_views.xml
> +</odoo>
Falta salto de línea pero aparte de esto, el módulo está incompleto ya que se pide que ambos campos aparezcan en el tree de OFs y de esta forma no se puede.
Hay que meter los 2 campos sumatorio calculados en la OF tal y como se describía en el claim.

2022-06-09 07:31 UTC, oihane requested changes
Si usas las configuraciones de pre-commit, podrás hacer los cambios de forma simple. Puedes encontrar en google más info.

2022-06-09 07:31 UTC, oihane commented on mrp_production_duration/__manifest__.py
> +}
Usar comillas dobles, en OCA tienen un script que los modifica.

2022-06-09 07:31 UTC, oihane commented on mrp_production_duration/models/mrp_production.py
> +from odoo import models, fields, api
Hay que ponerlos según orden alfabetico, el mismo script que se usa para cambiar a comillas dobles lo ordena.

2022-06-10 09:29 UTC, oihane approved these changes

2022-06-10 09:30 UTC, merged