[ADD] mrp_produciton_lot: When an OF is confirmed, automatically crea…
avanzosc/mrp-addons pull request #23
Opened 2019-01-15 10:52 UTC by alfredoavanzosc

…te a lot.
Crear automáticamente un lote cuando se confirma una OF.

2019-01-16 14:51 UTC, anajuaristi approved these changes

2019-01-16 15:41 UTC, alfredoavanzosc commented
@avanzosc/developers ... review please.

2019-01-17 10:30 UTC, Daniel-CA requested changes

2019-01-17 10:30 UTC, Daniel-CA commented on mrp_production_lot/models/stock_production_lot.py
> +            lot.write(vals)
Odoo recomienda no meter writes en onchanges, ¿no hay otra manera de hacer esto?

2019-01-17 10:33 UTC, Daniel-CA approved these changes

2019-01-17 10:33 UTC, merged