[16.0][MIG] quality_control_ref_search: Migration to 16.0
avanzosc/mrp-addons pull request #255
Opened 2023-12-28 11:18 UTC by unaiberis

2024-02-20 11:41 UTC, unaiberis commented
[16.0][MIG] quality_control_ref_search: Migration to 16.0

2024-03-01 12:04 UTC, oihane requested changes
Hay cambios en este PR que no corresponden

Corregir la dependencia, debe ser `quality_control_oca`

2024-03-01 12:27 UTC, anajuaristi approved these changes

2024-03-01 12:50 UTC, oihane requested changes
Hay cambios no relacionados con el modulo que se pretende añadir, eliminar dichos cambios

2024-05-03 07:46 UTC, anajuaristi approved these changes

2024-05-03 08:35 UTC, anajuaristi approved these changes

2024-05-03 08:38 UTC, oihane approved these changes

2024-06-17 10:47 UTC, merged