[ADD] mrp_production_erase
avanzosc/mrp-addons pull request #33
Opened 2019-07-11 09:40 UTC by Daniel-CA

2019-07-11 14:27 UTC, Daniel-CA commented
@avanzosc/developers review please

2019-07-11 14:30 UTC, oihane commented on mrp_production_erase/__manifest__.py
> +        ],
nirpicking
sobra una indentacion

2019-07-11 14:31 UTC, oihane commented on mrp_production_erase/__manifest__.py
> +    'auto_install': False,
Como por defecto es False, lo normal es omitirlo

2019-07-11 14:31 UTC, oihane commented on mrp_production_erase/tests/__init__.py
> +# Copyright (c) 2019 Daniel Campos <danielcampos@avanzosc.es> - Avanzosc S.L.
OCA dixit: Si el fichero no tiene codigo ejecutable, no es necesario añadir la licencia.

2019-07-11 14:33 UTC, oihane commented on mrp_production_erase/wizard/mrp_production_erase.py
> +            production.action_cancel()
y si por alguna razón no se pudiera cancelar (o diese un raise?) no sé si existe ese supuesto.

2019-07-11 14:33 UTC, oihane commented on mrp_production_erase/wizard/mrp_production_erase.py
> +            production.unlink()
Lo mismo con el unlink

2019-07-11 14:33 UTC, oihane commented on mrp_production_erase/wizard/mrp_production_erase_view.xml
> +<openerp>
estás en v12, se pone odoo, y no se pone data

2019-07-11 14:35 UTC, oihane commented on mrp_production_erase/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
deberias de añadir `https`
```python
License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
```

2019-07-11 14:36 UTC, oihane requested changes
Falta la traducción

2019-07-11 15:55 UTC, oihane commented on mrp_production_erase/wizard/mrp_production_erase.py
> +            production.action_cancel()
Mirando en el modulo mrp de OCB
```python
        if any(workorder.state == 'progress' for workorder in self.mapped('workorder_ids')):
            raise UserError(_('You can not cancel production order, a work order is still in progress.'))
```

2019-07-11 15:56 UTC, oihane commented on mrp_production_erase/wizard/mrp_production_erase.py
> +            production.unlink()
Sé que es redundante, pero yo pondría que solo borrase si está en estado = 'cancel'

2019-07-12 07:16 UTC, Daniel-CA commented on mrp_production_erase/wizard/mrp_production_erase.py
> +            production.action_cancel()
Al final he filtrado esos dos estados, 'cancelado' y 'realizado', que son en los que no se debería cancelar una orden

2019-07-12 07:17 UTC, Daniel-CA commented on mrp_production_erase/wizard/mrp_production_erase.py
> +            production.unlink()
Ahora es redundante si, pero si por lo que sea se añade un módulo que impide cancelar los otros estados no está de más meter ese control.

2019-07-12 07:42 UTC, oihane approved these changes

2019-07-12 07:43 UTC, oihane commented
En v12 odoo usa el *.pot (da un warning de que falta) no sé para que pero ahora se añade.

2019-07-12 07:50 UTC, Daniel-CA commented
> En v12 odoo usa el *.pot (da un warning de que falta) no sé para que pero ahora se añade.

Lo de siempre, yo lo añado pero el git me lo ignora.

2019-07-12 08:39 UTC, oihane approved these changes
LGTM

2019-07-24 13:37 UTC, alfredoavanzosc approved these changes
:+1:

2019-07-24 13:48 UTC, merged